name: Main MistralBot workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  build_bot_and_push_to_docker_hub:
    name: Push bot Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mistral_bot:latest
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_bot_and_push_to_docker_hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Logging into Docker Hub..."
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            echo "Updating Docker container..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/mistral_bot:latest
            
            echo "Stopping and removing old container..."
            sudo docker stop mistral_bot || true
            sudo docker rm mistral_bot || true
            
            echo "Starting new container..."
            sudo docker run --restart=on-failure -d \
              --name mistral_bot \
              -e API_ID="${{ secrets.API_ID }}" \
              -e API_HASH="${{ secrets.API_HASH }}" \
              -e BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
              -e API_TOKEN="${{ secrets.API_TOKEN }}" \
              -e MISTRAL_TOKEN="${{ secrets.MISTRAL_TOKEN }}" \
              ${{ secrets.DOCKER_USERNAME }}/mistral_bot:latest